### ISSUE TITLE
Implicit id field not set

### ISSUE THREAD

**Issue by fluffy-critter** [Jonesus/pony-stubs#4]
If I use the implicit int PrimaryKey field on an entity class, I get errors like `"type[Entry]" has no attribute "id"`. I can work around this by providing an explicit `id` field but that seems like it shouldn't be necessary.

**Comment by fluffy-critter** [comment]
Oh, the README covers this already, my bad.

**Comment by Jonesus** [comment]
This is a tricky question, as when the user declares a class like so

```python
class Customer(db.Entity):
   email = PrimaryKey(str)
   name = Required(str)
```

Pony won't create an `id` column, so defaulting to make each `Entity` have `id` field of any type seems like the wrong approach :thinking: I guess if we had a mypy plugin we could make an implicit `id` happen, but that's out of my expertise at least for now :smile:

**Comment by fluffy-critter** [comment]
Yeah, that's a good point too. I think adding the `id:int` annotation as explained in the README is fine.
